version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    parallelism: 1
    working_directory: ~/project
    shell: /bin/bash
    steps:
      - checkout
      # - run:
      #   name: test
      #   command: npm test
